- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.4.2
  hooks:
  - id: flake8
    language_version: 'python3.5'
    args: []
    additional_dependencies: ['pep8-naming']
- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: 1.0.4
  hooks:
  - id: python-import-sorter
    args: ['--check-only']
