dist: trusty
before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst python3-libhfst
script:
    - ./autogen.sh
    - ./configure
    - make
    - make check
    - cat test/test-suite.log
notifications:
    irc:
        channels:
            - "chat.freenode.net#omorfi"
        on_failure: always
        on_success: always

